"""AI monitoring data models."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    """Return timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


class InsightSeverity(str, Enum):
    """Severity levels for monitoring insights."""

    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"
    OPTIMIZATION = "optimization"


class InsightCategory(str, Enum):
    """Categories for monitoring insights."""

    RESOURCE = "resource"
    SECURITY = "security"
    AVAILABILITY = "availability"
    IMAGE = "image"
    OPTIMIZATION = "optimization"


class ContainerCapabilities(BaseModel):
    """Container security capabilities and configuration."""

    endpoint_id: int
    endpoint_name: str | None = None
    container_id: str
    container_name: str
    cap_add: list[str] = Field(default_factory=list)
    cap_drop: list[str] = Field(default_factory=list)
    privileged: bool = False
    security_opt: list[str] = Field(default_factory=list)
    elevated_risks: list[str] = Field(default_factory=list)


class ImageStatus(BaseModel):
    """Image update status from Portainer."""

    stack_id: int
    stack_name: str | None = None
    endpoint_id: int
    endpoint_name: str | None = None
    image_name: str
    current_digest: str | None = None
    latest_digest: str | None = None
    outdated: bool = False
    error: str | None = None


class MonitoringInsight(BaseModel):
    """Single monitoring insight generated by AI analysis."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=_utc_now)
    severity: InsightSeverity
    category: str
    title: str
    description: str
    affected_resources: list[str] = Field(default_factory=list)
    recommended_action: str | None = None


class MonitoringReport(BaseModel):
    """Complete monitoring analysis report."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=_utc_now)
    insights: list[MonitoringInsight] = Field(default_factory=list)
    summary: str = ""
    endpoints_analyzed: int = 0
    containers_analyzed: int = 0
    security_issues_found: int = 0
    outdated_images_found: int = 0


class InfrastructureSnapshot(BaseModel):
    """Snapshot of infrastructure state for analysis."""

    timestamp: datetime = Field(default_factory=_utc_now)
    endpoints_online: int = 0
    endpoints_offline: int = 0
    containers_running: int = 0
    containers_stopped: int = 0
    containers_unhealthy: int = 0
    security_issues: list[ContainerCapabilities] = Field(default_factory=list)
    outdated_images: list[ImageStatus] = Field(default_factory=list)
    endpoint_details: list[dict] = Field(default_factory=list)
    container_details: list[dict] = Field(default_factory=list)
    resource_usage: dict = Field(default_factory=dict)


__all__ = [
    "ContainerCapabilities",
    "ImageStatus",
    "InfrastructureSnapshot",
    "InsightCategory",
    "InsightSeverity",
    "MonitoringInsight",
    "MonitoringReport",
]
